name: Build And Deploy

on:
  workflow_dispatch:
    

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install packages
        run: |
          flutter pub get
          flutter build web --release --web-renderer html
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_RED_CLIFF_023876503 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "build/web" # App source code path
          api_location: "" # Api source code path - optional
          app_artifact_location: "build/web" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######